### ISSUE TITLE
Need an abstract

### ISSUE THREAD

**Issue by plehegar** [w3c/tt-profile-registry#15]
How about:
[[
This document is intended to provide a central location for enumerating identified TTML profiles, or, more strictly speaking, TTML decoder/processors, where each entry identifies a particular profile which is understood to implement a processor capable of satisfying the constraints of a defined TTML processor profile that takes the form of a TTML Profile Definition Document. It also contains the definition for the media type application/xml+ttml.
]]

**Comment by mikedo** [comment]
Maybe change the first sentence to: "This document is intended to provide a central location for the *_TTML media type definition and a registry of *_..."

Maybe we need to change the title to reflect this: "TTML Media Type Definition and Profile Registry"

**Comment by plehegar** [comment]
my preference would be to keep the title as-is since otherwise it would be quite long, but I don't have a strong opinion. @nigelmegitt , what do you think?

**Comment by plehegar** [comment]
I made a pull request to add the abstract. Mike, feel free to merge if you're happy. I'll wait to hear from Nigel on the title.

**Comment by mikedo** [comment]
I know it started out as just a registry, but the registry is in support of the "profile" parameter in the media type, so it is more comprehensively about the media type details, of which the registry is one component. "quite long"?  It's shorter than most Rec titles..

**Comment by plehegar** [comment]
As I said, I don't feel strongly about it. I'll send a separate PR to change the title and wait for Nigel to ok the change. Are you ok with merging the abstract in the meantime?

**Comment by nigelmegitt** [comment]
Regarding the title I can see both views here: a more accurately descriptive title will help people to discover the correct document; conversely a longer title is more cumbersome.

I'm almost tempted to suggest that we just call it "TTML Media Type Definition" since that's in many ways more important and the profiles registry is a subset of it. However now that many people have got used to the idea of calling it a profiles registry that doesn't seem very sensibly.

Since I'm on the fence here I propose to take the Editor's view.

**Comment by plehegar** [comment]
Mike, title and abstract updated. I'll let you figure out when to close this issue.
