### ISSUE TITLE
Abstract and status mismatch.

### ISSUE THREAD

**Issue by cconcolato** [w3c/tt-profile-registry#44]
The status of the document says:
> This is a registry and may be updated without any notices.

This sentence is confusing when you read the abstract which says that this document defines the MIME type.
I suggest replacing it with:

> This document may be updated without any notices.

**Comment by nigelmegitt** [comment]
It's also worth keeping the sense that the document contains a registry of codecs parameter values, perhaps in a separate sentence:

> This document contains a registry of values for the codecs parameter.

There may be better wording from a formal perspective, I'm not sure.

**Comment by cconcolato** [comment]
The abstract already carries that. I'm not sure it needs to be in the SotD.

**Comment by nigelmegitt** [comment]
Good point.

**Comment by skynavga** [comment]
The (current ED) status already states the document may be changed at any time. When we are ready to publish with NOTE status, then we can choose (if we want) to add a warning about updates due to being a registry, but, frankly, I think we need say nothing more in the SotD since we can always update a NOTE whether it is a registry or not. I will publish a PR that simply removes the offending text.
