### ISSUE TITLE
Which document defines TTML's MIME type

### ISSUE THREAD

**Issue by cconcolato** [w3c/tt-profile-registry#45]
The abstract says:
> This document defines the application/xml+ttml media type

But section 1 says:
> TTML defines a MIME type/subtype, application/ttml+xml, that may be used to identify the content type of TTML resources

And section 2 says:
> This section updates the media type, "application/ttml+xml" to add a new parameter, codecs. All other provisions of the media type specification remain the same. This supersedes the initial registration information in TTML 1.0 Second Edition.

First, I would suggest replacing the abstract text with the first sentence of section 2.
Then, I would suggest removing the 3rd sentence of section 2 because a NOTE cannot supersede a REC.
Finally, now that there are 2 TTML specifications, this should be updated.

**Comment by nigelmegitt** [comment]
The Note can and does supersede the Rec when it comes to the MIME type registration.

Happy to review a pull request addressing this. Note there's already #37 for the MIME type actually being wrong in the abstract.

**Comment by palemieux** [comment]
References to TTML1 2ED should be updated to TTML1 3ED

**Comment by nigelmegitt** [comment]
I don't think the 2ED reference for the original media type registration should be changed to 3ED, as in:

> This supersedes the initial registration information in [TTML 1.0 Second Edition](http://www.w3.org/TR/2013/REC-ttml1-20130924/)

since that was indeed the initial registration information.

We can update the other 2ED references when we know the final TTML1 3Ed Rec URL.

**Comment by skynavga** [comment]
The cited text from section 1 and 2 no longer exists due to recent PRs. The remaining relevant text, all of which states that this document is the defining document, can be found under:

**Abstract**

This document defines the application/ttml+xml media type ...

**§1 Purpose**

This document serves two purposes: (1) to define the Media Type application/ttml+xml, ...

**§2 Media Type Registration**

This section defines the media type "application/ttml+xml", ...

This updated definition supersedes the initial registration information specified in [TTML1-1e], Appendix C, as updated by [TTML1-2e], Appendix C.

Consequently, no ambiguity exists with respect to indicating the defining document. Closing this issue as moot.
